### ISSUE TITLE
Screen rebranded to Pop (Meetings), pop.com

### ISSUE THREAD

**Issue by ElijahLynn** [captn3m0/aur-screen-desktop-bin#10]
See https://pop.com/screenhero for announcement.

**Comment by captn3m0** [comment]
Thanks, will be taking this up soon 👍🏼

**Comment by ElijahLynn** [comment]
> Thanks, will be taking this up soon 👍🏼

Thank you for the time you put into making this available in the AUR!

**Comment by captn3m0** [comment]
- [x] New AUR package published at https://aur.archlinux.org/packages/pop-bin
- [x] GitHub repo renamed to `aur-pop-bin`
- [x] Submitted merge request to migrate votes/comments on AUR.

Closing this.
