### ISSUE TITLE
Update to v1.2.8

### ISSUE THREAD

**Issue by jsherwani** [captn3m0/aur-screen-desktop-bin#3]
Hello — Screen founder here 👋 

Thanks for maintaining this package!

In case it's helpful, https://scrn-prod.firebaseio.com/appUpdate/linux/latest.json points to the current latest version and is updated as part of our build process. We just pushed an update and I thought I'd let you know about the json file if it's easy to tie into your process.

**Comment by captn3m0** [comment]
This is very helpful! Going to set a notification for that.
